### ISSUE TITLE
VS Code launch config still uses `dotenv` package

### ISSUE THREAD

**Issue by jschirrmacher** [lacuna-tech/mds-core#1009]
With https://github.com/lacuna-tech/mds-core/pull/962, instead of `dotenv` the `dotenv-flow` library is used in mds-core. However, the VSCode launch configuration still tries to use `dotenv` - and fails.

**Comment by d-koppenhagen** [comment]
@jschirrmacher I think this issue can be closed as it's merged already (#1010)
