### ISSUE TITLE
Hardcoded lat/long coordenates prevent usage outside the US(?)

### ISSUE THREAD

**Issue by jaimeventura** [lacuna-tech/mds-core#576]
Hey,
When using mds-agency in Portugal i got the following error:

```
"error":"invalid_data","error_description":"None of the provided data was valid","error_details":

[
  "bad telemetry for device_id 08d65697-72ee-45b2-8070-ecd55b31b6e1: invalid lng -8.682058333333334"
]
```

Looking at the code, i found that its validating bounds, which i believe values are hard coded for the US: https://github.com/lacuna-tech/mds-core/blob/33243097e4712f5d9fbd0455dcab8f1d75172255/packages/mds-agency/utils.ts#L199-L204 :(

In the meantime, i'll change these to suite Portugal bounds, but could you fix this? Put these in a config file, maybe?

Thank you

**Comment by avatarneil** [comment]
Definitely something we can fix up; honestly, I don't even know how worth having it in a config is for the time being, I'd rather just completely remove it for this ingress layer. @karcass what do you think?

**Comment by karcass** [comment]
Yeah, let's junk it @avatarneil.
