### ISSUE TITLE
/geographies response not MDS compliant

### ISSUE THREAD

**Issue by mrsimpson** [lacuna-tech/mds-core#974]
## `tl;dr`

Reading geographies is not fully MDS compliant: `mds-geography-api` wraps the data in a `data` property and is lacking the `updated` property.

## Details

Currently, a `GET` to `/geographies` returns 
```
{
  version,
  data: geography/geographies
}
```

 As per [the MDS geographies API spec](https://github.com/openmobilityfoundation/mobility-data-specification/tree/main/geography#endpoints), it is expected to return `geography/geographies` right at the root *and* and additional `updated` property containing a timestamp.

Also, `GET /geographies/:id` returns the same result format with a single geography wrapped in the `geographies` array. This is also not expected, the payload is expected to return a single geography.

**Comment by avatarneil** [comment]
@mrsimpson the version of the MDS standard you linked is the latest, but mds-core currently supports v1.0.0. In the v1.0.0 spec, the response payload was different, see https://github.com/openmobilityfoundation/mobility-data-specification/tree/release-1.0.0/policy#geographies.

I think this issue can be closed.

**Comment by mrsimpson** [comment]
*phew* 😌
